import "../CSS/Blog.css"

interface blog {
    id: number,
    title: string,
    text: string,
    img: string,
}

const Posts: blog[] = [
    {id:1, title:"My Journey with The Catalyst Project", text:"Starting something of your own is always an adventure, a mix of excitement and uncertainty. For me, that adventure began with an idea—The Catalyst Project. As someone passionate about technology and entrepreneurship, I always dreamed of creating something meaningful, and this project became the perfect launchpad for my aspirations. The journey began with a simple question: How can I create something impactful that helps others? That question soon led to The Catalyst Project—a platform designed to bridge the gap between aspiring entrepreneurs and essential resources. In the beginning, it was just an idea on paper, but I knew it had the potential to be much more. The first challenge was to turn this idea into a reality. As someone with a background in web development, I decided to build the platform myself. HTML, CSS, and JavaScript became my best friends as I spent countless hours designing and developing the website. I focused on creating a clean, user-friendly interface that would provide a seamless experience for users. It wasn't just about the code—it was about the experience I wanted to offer. Every journey has its challenges, and The Catalyst Project was no exception. From debugging tricky code to designing a responsive layout, there were moments of frustration. But each challenge taught me something new, pushing me to become a better developer. One of the biggest hurdles was ensuring that the website was both functional and visually appealing. I wanted it to be more than just a platform—I wanted it to be an experience. After weeks of hard work, The Catalyst Project finally went live on February 20, 2025. Seeing the website I had built from scratch go live was a surreal moment. It was more than just a website—it was a dream turned into reality. But launch day was just the beginning. I knew there was still much more to learn, improve, and build upon. The Catalyst Project is not just a finished product; it is a constantly evolving journey. I continue to learn, adapt, and enhance the platform, ensuring it remains relevant and valuable to its users. Looking back, I realize that this journey has been about much more than just building a website. It has been a journey of growth, resilience, and passion. The Catalyst Project is a reminder that with dedication, persistence, and a willingness to learn, even the simplest ideas can turn into something impactful. And for me, this journey is just getting started. If you are someone with an idea, don’t hesitate. Start small, learn as you go, and never stop pushing forward. That’s what The Catalyst Project is all about."

    , img:""},

    {id:2, title:"Business Thinking And Entrepreneurship", text:"Starting something of your own is always an adventure, a mix of excitement and uncertainty. For me, that adventure began with an idea—The Catalyst Project. As someone passionate about technology and entrepreneurship, I always dreamed of creating something meaningful, and this project became the perfect launchpad for my aspirations. The journey began with a simple question: How can I create something impactful that helps others? That question soon led to The Catalyst Project—a platform designed to bridge the gap between aspiring entrepreneurs and essential resources. In the beginning, it was just an idea on paper, but I knew it had the potential to be much more. The first challenge was to turn this idea into a reality. As someone with a background in web development, I decided to build the platform myself. HTML, CSS, and JavaScript became my best friends as I spent countless hours designing and developing the website. I focused on creating a clean, user-friendly interface that would provide a seamless experience for users. It wasn't just about the code—it was about the experience I wanted to offer. Every journey has its challenges, and The Catalyst Project was no exception. From debugging tricky code to designing a responsive layout, there were moments of frustration. But each challenge taught me something new, pushing me to become a better developer. One of the biggest hurdles was ensuring that the website was both functional and visually appealing. I wanted it to be more than just a platform—I wanted it to be an experience. After weeks of hard work, The Catalyst Project finally went live on February 20, 2025. Seeing the website I had built from scratch go live was a surreal moment. It was more than just a website—it was a dream turned into reality. But launch day was just the beginning. I knew there was still much more to learn, improve, and build upon. The Catalyst Project is not just a finished product; it is a constantly evolving journey. I continue to learn, adapt, and enhance the platform, ensuring it remains relevant and valuable to its users. Looking back, I realize that this journey has been about much more than just building a website. It has been a journey of growth, resilience, and passion. The Catalyst Project is a reminder that with dedication, persistence, and a willingness to learn, even the simplest ideas can turn into something impactful. And for me, this journey is just getting started. If you are someone with an idea, don’t hesitate. Start small, learn as you go, and never stop pushing forward. That’s what The Catalyst Project is all about."
            
    , img:""},

    {id:3, title:"Journey In Web And App Development", text:"My journey in web and app development began with a simple curiosity—how do websites work? What goes behind those sleek designs and interactive interfaces? As I delved deeper, this curiosity turned into a passion, and I found myself spending countless hours exploring HTML, CSS, and JavaScript. But my real growth came when I started building projects. One of my most impactful projects has been The Catalyst Project, a mentorship platform for JEE aspirants, where, as the CTO, I led the development of the platform’s website, ensuring a seamless user experience with a clean, intuitive design. From coding the front end to optimizing the user interface, I learned the importance of balancing aesthetics with functionality. Another exciting venture was my role as the Web and Tech Coordinator for Techfest CA at IIT Bombay, where I collaborated with the team to design and develop the CA website, ensuring a smooth and engaging experience for all users. But the journey didn’t stop at web development—I also ventured into app development. Working with Kotlin, I helped design and develop the Techfest CA app, bringing the same level of user-centric design to mobile platforms. Web and app development have become more than just skills—they are my creative outlet, a way to turn ideas into reality. With every new project, I explore new technologies, face new challenges, and most importantly, learn something new. And as I continue this journey, I’m excited to keep creating, building, and transforming ideas into experiences."  
    
    , img:""},

    {id:4, title:"A New Beginning: My Journey at IIT Bombay", text:"stepping onto the lush green campus of IIT Bombay for the first time was like walking into a dream. Surrounded by towering trees, tranquil lakes, and the soothing sound of rustling leaves, I found myself mesmerized by the sheer beauty of the campus. Little did I know that this serene environment would become the backdrop of an unforgettable adventure.In the beginning, I was almost obsessed with exploring every corner of this beautiful campus. Mornings often began with walks around the scenic Powai Lake, and lazy afternoons were spent lounging under the shade of the massive banyan trees. The greenery wasn’t just a sight—it was a feeling, a calm escape in the midst of a bustling academic world.But IIT Bombay is much more than just its natural beauty. Soon, I found myself diving headfirst into the vibrant campus life. I tried everything—culturals, sports, and tech. From cheering at the electrifying dance battles of cultural fests to feeling the adrenaline of sports tournaments, I was everywhere. I even found myself exploring the world of technology, meeting passionate seniors who were always ready to teach something new.Of course, academics were there, but let’s be honest—I studied less and enjoyed a lot more. Late-night chai runs with friends, spontaneous trips to Vihar Lake, and endless conversations under the starry sky became a routine. Our rooms were more than just places to sleep; they were our world, filled with laughter, music, and memories.As the semester approached its end, we decided to take our exploration beyond the campus. Mumbai—The City of Dreams—was waiting, and we weren’t going to miss it. From the bustling streets of Colaba to the peaceful sunsets at Marine Drive, every trip was a story of its own. Whether it was the thrill of traveling in local trains or the taste of vada pav at Juhu Beach, Mumbai had a charm that left us in awe.Looking back, my first few months at IIT Bombay were not just a chapter in my life—it was a journey of self-discovery, filled with unforgettable experiences, new friendships, and a whole lot of memories. And as I step forward, I carry with me the lessons, the joy, and the spirit of those magical days."  
    
    , img:""},

    {id:5, title:"My Love For Photography", text:"My journey into business thinking and entrepreneurship didn’t start with grand plans or a desire for fame—it began with curiosity. I have always been fascinated by the stories of successful startups, the way a simple idea can transform into a thriving venture. But for me, entrepreneurship is not just about starting a business—it’s about identifying problems, finding innovative solutions, and creating value.My first real step into this world was with The Catalyst Project—a mentorship platform for JEE aspirants. As the CTO, I didn’t just focus on the technical side; I also learned to think about user needs, marketing strategies, and growth. It was here that I realized the importance of understanding both the technical and business aspects of a project. I learned that a great product is nothing without a clear value proposition and a solid strategy to reach the right audience.Beyond The Catalyst Project, my role as the Web and Tech Coordinator for Techfest CA at IIT Bombay also exposed me to the business side of things. Collaborating with a team, planning user experiences, and ensuring that the platform met the needs of its users—all of these experiences taught me how to balance innovation with practicality.Entrepreneurship, for me, is a mindset—a way of looking at the world with curiosity, constantly seeking opportunities, and never being afraid to take risks. Whether it’s launching a startup, building a product, or simply solving a problem, I’ve learned that success comes from a blend of creativity, strategy, and resilience. And as I continue to grow, I look forward to exploring new ideas, building impactful solutions, and creating value wherever I go."
            
    , img:""},
    
]

const Blog = () => {
    return(
        <div>
            <div className="Blog-Container">
                {Posts.map((item) => (
                    <div className="Blog-card" key={item.id}>
                        <h1 className="Blog-title">{item.title}</h1>
                        <p className="Blog-Description">{item.text}</p>
                        <img className="Blog-image" src={item.img}></img>
                    </div>
                ))}
            </div>
        </div>
    )
}

export default Blog;